import { Toaster } from "sonner"
import type { Metadata } from "next";
import "./globals.css";
import { ConvexClientProvider } from "@/components/providers/convex-provider";
import { EdgeStoreProvider } from "@/lib/edgestore";


export const metadata: Metadata = {
    title: "BoccNote",
    description: "Generated by create next app",
};

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang="en" suppressContentEditableWarning>
            <body>
                <ConvexClientProvider>
                    <EdgeStoreProvider>

                        <Toaster position="bottom-center" />
                        {children}

                    </EdgeStoreProvider>
                </ConvexClientProvider>
            </body>
        </html>
    );
}
