import type { Metadata } from "next";
import "./globals.css";



export const metadata: Metadata = {
    title: "BoccNote",
    description: "Generated by create next app",
};

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang="en" suppressContentEditableWarning>
            <body>


                {children}


            </body>
        </html>
    );
}
